import { useState, useEffect } from 'react'
import { useSupabaseClient } from '@supabase/auth-helpers-react'
import md from 'markdown-it'
import Layout from '../../../components/Layout.js'

export default function Contacts({
  id
}) {
  const [contact, setContact] = useState(null);
  const supabase = useSupabaseClient();

  useEffect(() => {
    const fetchData = async () => {
      try {
        let { data, error, status } = await supabase
          .from('contacts')
          .select(`id, firstname, lastname, email, message`)
          .eq('id', id)
          .single();

        if (error) {
          throw error;
        }

        setContact(data);
      } catch (error) {
        console.error('Error fetching contact:', error.message);
      }
    };

    fetchData();
  }, [id]);

  
  return (
    <Layout
      title="Admin Contacts"
      description="Generated by create next app"
      >
      <h1 className='wt-title'>
        View a contact message
      </h1>
      {contact && (
        <div >
          <div className="wt-affichage" >
            
              Name:{contact.firstname} {contact.lastname}
              <br/>
              Email:{contact.email}
              
           
          </div>
          <br/>
          <div className="wt-textemess">
            <div dangerouslySetInnerHTML={{ __html: typeof contact.message === 'string' ? md().render(contact.message).toString():''}} />
          </div>
        </div>
      )}
    </Layout>
  )
}

export async function getServerSideProps(context) {
  return {
    props: {
      id: context.params.id
    },
  }
}
