import { useState } from 'react'
import { useSupabaseClient } from '@supabase/auth-helpers-react'
import Layout from '../components/Layout.js'
import { useUser } from '/components/UserContext.js';


export default function Page() {
  const supabase = useSupabaseClient();
  const [message, setMessage] = useState(null);
  const { user } = useUser();
  const currentTimestamp = new Date().toISOString();


  const onSubmit = async function (e) {
    e.preventDefault();
  
    const formData = new FormData(e.target);
    const data = {};
  
    formData.forEach((value, key) => {
      data[key] = value;
    });
  
    try {
      const { data: newContact, error } = await supabase
        .from('travels')
        .upsert([{ ...data, Travelemail: user.email, }]);  
      if (error) {
        throw error;
      }
  
      // Log or handle success for the first upsert
      console.log('Upsert successful:', newContact);
    } catch (error) {
      console.error('Error in the  upsert:', error);
    }
  };
  
  return (
    <Layout
      title="Contacts"
      description="Generated by create next app"
    >
      <h1 className='wt-title'>
        Travels
      </h1>
      <form className="[&_span]:block grid gap-3" onSubmit={onSubmit}>
        <div>
          <label>
            <span>Who traveled ?</span>
            <input type="text" name="TravelerName" />
          </label>
        </div>
        <div>
          <label>
            <span>Where did you travel ?</span>
            <input type="text" name="TravelDest" />
          </label>
        </div>
        <div>
          <label>
            <span>How many days did you stay?</span>
            <input type="text" name="TravelDays" />
          </label>
        </div>
        <div>
          <label>
            <span>How did you travel ?</span>
            <input type="text" name="TravelTools" />
          </label>
        </div>
        <div>
          <label>
            <span>Tell us about your trip</span>
            <textarea name="TravelStory" />
          </label>
        </div>
        <div>
          <button
            className="rounded py-1 px-3 text-white bg-slate-500 hover:bg-blue-500"
          >
            Send
          </button>
        </div>
      </form>
      {message &&
        <div
          aria-label="Overlow below the drawer dialog"
          className="fixed inset-0 bg-black/80 flex items-center justify-center"
          onClick={() => setMessage(null)}
          role="dialog"
        >
          <div
            aria-label="Alert pane"
            className="max-h-[90vh] max-w-[95vw] overflow-auto p-4 prose bg-white"
          >
            {message}
          </div>
        </div>
      }
    </Layout>
  )
}