import { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Layout from '../components/Layout.js'

export default function Page() {
  const [articles, setArticles] = useState([])
  useEffect(() => {
    async function fetchData() {
      try {
        const response = await fetch('/api/articles');
        const data = await response.json();
        console.log('Data from API:', data);
        setArticles(data);
      } catch (error) {
        console.error('Error fetching data:', error);
      }
    }

    fetchData()
  }, [])

  return (
    <Layout>
      <Head>
        <title>WebTech - articles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="wt-center">
      <div className="wt-welcome">
        ARTICLES
      </div>
      </main>
      <br/><br/>
      <p className='wt-texte'>Click on the article title, to see more details</p>
      <br/><br/>
      <div className="flex justify-center">
        <table className="table">
          <tbody>
            {articles.map((article) => (
              <tr key={article.id}>
                <td className="wt-articles">
                  <Link href={`/articles/${article.id}`}>{article.title}</Link>
                </td>
                <td className="wt-content">{article.content}</td>

              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </Layout>
  )
}
