import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { ChevronRightIcon } from '@heroicons/react/20/solid';
import Layout from '/components/Layout.js';
import { useSupabaseClient } from '@supabase/auth-helpers-react';

export default function Contacts() {
  const [travels, setTravels] = useState([]);
  const supabase = useSupabaseClient();

  useEffect(() => {
    (async () => {
      let { data, error, status } = await supabase
        .from('travels')
        .select(`id, TravelerName, TravelDest, TravelDays, TravelStory`);
      setTravels(data);
    })();
  }, []);

  return (
    <Layout
      title="Admin Contacts"
      description="Generated by create next app"
    >
      <br/><br/><br/>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {travels.map((travel) => (
          <div key={travel.id} className="bg-white overflow-hidden shadow rounded-lg">
            <div className="p-4">
              <h3 className="text-4xl font-bold mb-2 ">{travel.TravelDest}</h3>
              <p className="text-slate-500 mb-2">{travel.TravelerName}</p>
              <p className="text-slate-500">{travel.TravelDays} </p>
              <p className="text-slate-500 mt-2">{travel.TravelStory.slice(0,100)} ....</p>
            </div>
            <div className="p-4 flex items-center justify-center">
              <Link href={`/travels/${travel.id}`} className="w-5 h-5 block bg-slate-200 hover:bg-blue-500 hover:text-white rounded-full">
                <ChevronRightIcon className="h-5 w-5" aria-hidden="true" />
              </Link>
            </div>
          </div>
        ))}
      </div>
    </Layout>
  );
}
