import Head from 'next/head'
import Layout from '../../components/Layout.js'
import { db } from '../api/articles';


export async function getStaticProps(ctx) {
    const { id } = ctx.params;
    const article = db.find((a) => a.id === id);
    return {
        props: {
            article,
        },
    };
}

export async function getStaticPaths() {
    const paths = db.map((article) => ({
        params: { id: article.id.toString() },
    }));

    return {
        paths,
        fallback: false,
    };
}


export default function Article({article}) {

  return (
    <Layout>
      <Head>
        <title>WebTech - articles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="wt-center">
      <div className="wt-welcome">
        {article.title}
      </div>
      
      <div className='wt-texte'>
      <br/><br/>
         {article.content}<br/>
         Author : {article.author}<br/>
         Date : {article.date}
      </div>
      </main>
    </Layout>
  )
}